baseURL = "https:/dailywire.news/"
languageCode = "en-us"
theme = "newsroom"

[author]
  name = "Kristian Jones"

[languages]
  [languages.en]
    keywords = ""
    homeSubtitle = "Programmer, Server/System Administrator, Solution Integrator"
    readOtherPosts = "Read other posts"
    title = "Kristian Jones"

  [languages.en.params.logo]
    logoHomeLink = "/"
    logoText = "kristianjones.dev"

# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name       = "About"
#     url        = "/about"
#     weight     = 1
#   [[menu.main]]
#     identifier = "blog"
#     name       = "Blog"
#     url        = "/posts"
#     weight     = 2
#   [[menu.main]]
#     identifier = "resume"
#     name       = "Resume"
#     url        = "/nc_resume.pdf"
#     weight     = 3